version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'

  web:
    build: .
    ports:
      - 8001:8000
      - 5556:5555
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=fastapi
      - DATABASE_URL=mongodb://admin:password123@host.docker.internal:6000/fastapi?authSource=admin
      - ACCESS_TOKEN_EXPIRES_IN=3600
      - REFRESH_TOKEN_EXPIRES_IN=86400
      - JWT_ALGORITHM=HS256
      - CLIENT_ORIGIN=http://localhost:3000
      - SECRET_KEY =secret
      - SMTP_PROVIDER=gmail
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=martinjoey2j618@gmail.com
      - SMTP_PASSWORD=rdiczfulcmdqcrhf
      - CELERY_BROKER_URL=redis://celerybackend:6379/0
      - CELERY_RESULT_BACKEND=redis://celerybackend:6379/0
    depends_on:
      - celerybackend

  celerybackend:
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

volumes:
  mongo:
